sudo: required
services:
  - docker

before_install:
  - docker build -t vkrishna11/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vkrishna11/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-232756010747"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

